apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-db-v2
  namespace: tienda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tienda-db-v2  
  template:
    metadata:
      labels:
        app: tienda-db-v2  
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "false"
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          emptyDir: {}
        - name: init-script
          configMap:
            name: tienda-db-init-v2  # 👈 Le diremos que busque el nuevo configmap v2