name: Deploy to Amazon EKS

on:
  push:
    branches: [ "main" ] # El pipeline se ejecutará cada vez que subas cambios a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Obligatorio para cuentas AWS Academy / Vocareum
        aws-region: us-east-1

    - name: Iniciar sesion en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 1. NUEVO: Configura el constructor Docker Buildx necesario para gestionar la caché avanzada
    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 2. NUEVO: Compila y sube el Backend utilizando el almacenamiento de caché de GitHub (gha)
    - name: Compilar y subir Backend a ECR
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/tienda-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # 3. NUEVO: Compila y sube el Frontend utilizando el almacenamiento de caché de GitHub (gha)
    - name: Compilar y subir Frontend a ECR
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/tienda-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Actualizar configuracion de Kubeconfig
      run: |
        aws eks update-kubeconfig --name devopseks --region us-east-1

    - name: Desplegar en EKS
      run: |
        # Reemplaza la palabra REGISTRY_PROXY por la URL real de tu ECR en todos los archivos yaml
        sed -i "s|REGISTRY_PROXY|${{ steps.login-ecr.outputs.registry }}|g" k8s/*.yaml
        
        # Aplica los manifiestos corregidos
        kubectl apply -f k8s/
        
        # Fuerza el reinicio para descargar las nuevas versiones
        kubectl rollout restart deployment/tienda-backend -n tienda
        kubectl rollout restart deployment/tienda-frontend -n tienda

        # NUEVO: Esperar y validar activamente que los nuevos pods estén saludables
        echo "Validando la estabilidad del despliegue en Kubernetes..."
        kubectl rollout status deployment/tienda-backend -n tienda --timeout=3m
        kubectl rollout status deployment/tienda-frontend -n tienda --timeout=3m
